//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERUV_WAP.wsNotif_DVLP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsNotif_DVLP.InotifService")]
    public interface InotifService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InotifService/pCreaNotif", ReplyAction="http://tempuri.org/InotifService/pCreaNotifResponse")]
        string pCreaNotif(string strDatos, string opcion, string KeyWsSeruv, string strMailsTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InotifService/pCreaNotif", ReplyAction="http://tempuri.org/InotifService/pCreaNotifResponse")]
        System.Threading.Tasks.Task<string> pCreaNotifAsync(string strDatos, string opcion, string KeyWsSeruv, string strMailsTo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InotifServiceChannel : SERUV_WAP.wsNotif_DVLP.InotifService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InotifServiceClient : System.ServiceModel.ClientBase<SERUV_WAP.wsNotif_DVLP.InotifService>, SERUV_WAP.wsNotif_DVLP.InotifService {
        
        public InotifServiceClient() {
        }
        
        public InotifServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InotifServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InotifServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InotifServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string pCreaNotif(string strDatos, string opcion, string KeyWsSeruv, string strMailsTo) {
            return base.Channel.pCreaNotif(strDatos, opcion, KeyWsSeruv, strMailsTo);
        }
        
        public System.Threading.Tasks.Task<string> pCreaNotifAsync(string strDatos, string opcion, string KeyWsSeruv, string strMailsTo) {
            return base.Channel.pCreaNotifAsync(strDatos, opcion, KeyWsSeruv, strMailsTo);
        }
    }
}
