//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERUV_WAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srvxaddweb/WSPortal/wsSistemas/wsgetinfoempleado/wsgetinfoempleado.asmx")]
        public string SERUV_WAP_srvxaddweb_wsGetInfoEmpleado {
            get {
                return ((string)(this["SERUV_WAP_srvxaddweb_wsGetInfoEmpleado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dsia.uv.mx/WSPortal/wsSistemas/wsGetInfoEmpleado/wsGetInfoEmpleado.asmx")]
        public string SERUV_WAP_wsGetInfoEmpleado_PROD_wsGetInfoEmpleado {
            get {
                return ((string)(this["SERUV_WAP_wsGetInfoEmpleado_PROD_wsGetInfoEmpleado"]));
            }
        }
    }
}
