//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERUV_WAP.wsADPrincipal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosAD", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DatosAD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoCampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCampusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoCampus {
            get {
                return this.NoCampusField;
            }
            set {
                if ((object.ReferenceEquals(this.NoCampusField, value) != true)) {
                    this.NoCampusField = value;
                    this.RaisePropertyChanged("NoCampus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCampus {
            get {
                return this.NombreCampusField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCampusField, value) != true)) {
                    this.NombreCampusField = value;
                    this.RaisePropertyChanged("NombreCampus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salida", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Salida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsADPrincipal.IServAD")]
    public interface IServAD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/obtieneInformacionUsuarioAD", ReplyAction="http://tempuri.org/IServAD/obtieneInformacionUsuarioADResponse")]
        SERUV_WAP.wsADPrincipal.DatosAD obtieneInformacionUsuarioAD(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/obtieneInformacionUsuarioAD", ReplyAction="http://tempuri.org/IServAD/obtieneInformacionUsuarioADResponse")]
        System.Threading.Tasks.Task<SERUV_WAP.wsADPrincipal.DatosAD> obtieneInformacionUsuarioADAsync(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/usuarioADValido", ReplyAction="http://tempuri.org/IServAD/usuarioADValidoResponse")]
        bool usuarioADValido(string idUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/usuarioADValido", ReplyAction="http://tempuri.org/IServAD/usuarioADValidoResponse")]
        System.Threading.Tasks.Task<bool> usuarioADValidoAsync(string idUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/usuarioADValidoDocente", ReplyAction="http://tempuri.org/IServAD/usuarioADValidoDocenteResponse")]
        SERUV_WAP.wsADPrincipal.Salida usuarioADValidoDocente(string idUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/usuarioADValidoDocente", ReplyAction="http://tempuri.org/IServAD/usuarioADValidoDocenteResponse")]
        System.Threading.Tasks.Task<SERUV_WAP.wsADPrincipal.Salida> usuarioADValidoDocenteAsync(string idUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/existeUsuarioAD", ReplyAction="http://tempuri.org/IServAD/existeUsuarioADResponse")]
        bool existeUsuarioAD(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/existeUsuarioAD", ReplyAction="http://tempuri.org/IServAD/existeUsuarioADResponse")]
        System.Threading.Tasks.Task<bool> existeUsuarioADAsync(string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/actualizaPasswordUsuario", ReplyAction="http://tempuri.org/IServAD/actualizaPasswordUsuarioResponse")]
        bool actualizaPasswordUsuario(string campus, string idUsuario, string passwordOld, string passwordNew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServAD/actualizaPasswordUsuario", ReplyAction="http://tempuri.org/IServAD/actualizaPasswordUsuarioResponse")]
        System.Threading.Tasks.Task<bool> actualizaPasswordUsuarioAsync(string campus, string idUsuario, string passwordOld, string passwordNew);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServADChannel : SERUV_WAP.wsADPrincipal.IServAD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServADClient : System.ServiceModel.ClientBase<SERUV_WAP.wsADPrincipal.IServAD>, SERUV_WAP.wsADPrincipal.IServAD {
        
        public ServADClient() {
        }
        
        public ServADClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServADClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServADClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServADClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SERUV_WAP.wsADPrincipal.DatosAD obtieneInformacionUsuarioAD(string idUsuario) {
            return base.Channel.obtieneInformacionUsuarioAD(idUsuario);
        }
        
        public System.Threading.Tasks.Task<SERUV_WAP.wsADPrincipal.DatosAD> obtieneInformacionUsuarioADAsync(string idUsuario) {
            return base.Channel.obtieneInformacionUsuarioADAsync(idUsuario);
        }
        
        public bool usuarioADValido(string idUsuario, string password) {
            return base.Channel.usuarioADValido(idUsuario, password);
        }
        
        public System.Threading.Tasks.Task<bool> usuarioADValidoAsync(string idUsuario, string password) {
            return base.Channel.usuarioADValidoAsync(idUsuario, password);
        }
        
        public SERUV_WAP.wsADPrincipal.Salida usuarioADValidoDocente(string idUsuario, string password) {
            return base.Channel.usuarioADValidoDocente(idUsuario, password);
        }
        
        public System.Threading.Tasks.Task<SERUV_WAP.wsADPrincipal.Salida> usuarioADValidoDocenteAsync(string idUsuario, string password) {
            return base.Channel.usuarioADValidoDocenteAsync(idUsuario, password);
        }
        
        public bool existeUsuarioAD(string idUsuario) {
            return base.Channel.existeUsuarioAD(idUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> existeUsuarioADAsync(string idUsuario) {
            return base.Channel.existeUsuarioADAsync(idUsuario);
        }
        
        public bool actualizaPasswordUsuario(string campus, string idUsuario, string passwordOld, string passwordNew) {
            return base.Channel.actualizaPasswordUsuario(campus, idUsuario, passwordOld, passwordNew);
        }
        
        public System.Threading.Tasks.Task<bool> actualizaPasswordUsuarioAsync(string campus, string idUsuario, string passwordOld, string passwordNew) {
            return base.Channel.actualizaPasswordUsuarioAsync(campus, idUsuario, passwordOld, passwordNew);
        }
    }
}
