//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SERUV_WAP.wsGetInfoEmpleado_DVLP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsGetInfoEmpleadoSoap", Namespace="http://xalapa.intra.uv.mx/")]
    public partial class wsGetInfoEmpleado : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback funGetInfoEmpleadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsGetInfoEmpleado() {
            this.Url = global::SERUV_WAP.Properties.Settings.Default.SERUV_WAP_srvxaddweb_wsGetInfoEmpleado;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event funGetInfoEmpleadoCompletedEventHandler funGetInfoEmpleadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xalapa.intra.uv.mx/funGetInfoEmpleado", RequestNamespace="http://xalapa.intra.uv.mx/", ResponseNamespace="http://xalapa.intra.uv.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string funGetInfoEmpleado(string sLogin, string sBD, string sKey) {
            object[] results = this.Invoke("funGetInfoEmpleado", new object[] {
                        sLogin,
                        sBD,
                        sKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void funGetInfoEmpleadoAsync(string sLogin, string sBD, string sKey) {
            this.funGetInfoEmpleadoAsync(sLogin, sBD, sKey, null);
        }
        
        /// <remarks/>
        public void funGetInfoEmpleadoAsync(string sLogin, string sBD, string sKey, object userState) {
            if ((this.funGetInfoEmpleadoOperationCompleted == null)) {
                this.funGetInfoEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfunGetInfoEmpleadoOperationCompleted);
            }
            this.InvokeAsync("funGetInfoEmpleado", new object[] {
                        sLogin,
                        sBD,
                        sKey}, this.funGetInfoEmpleadoOperationCompleted, userState);
        }
        
        private void OnfunGetInfoEmpleadoOperationCompleted(object arg) {
            if ((this.funGetInfoEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.funGetInfoEmpleadoCompleted(this, new funGetInfoEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void funGetInfoEmpleadoCompletedEventHandler(object sender, funGetInfoEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class funGetInfoEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal funGetInfoEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591